export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SEARCH_USERS = 'GET_USERS';
export const SEARCH_USERS_ERROR = 'GET_USERS_ERROR';
export const CLEAR_USERS = 'CLEAR_USERS';
export const LOADING_USERS = 'LOADING_USERS';


export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR';
export const LOADING_USER_DETAIL = 'LOADING_USER_DETAIL';

export const GET_USER_REPOS = 'GET_USER_REPOS';
export const GET_USER_REPOS_ERROR = 'GET_USER_REPOS_ERROR';
export const LOADING_USER_REPOS = 'LOADING_USER_REPOS';